# Tell travis that we need super user level permission,
# since it's required to make use of docker.
sudo: required
services:
    - docker # tell travis that we need a copy of docker

# `before_install` contains a series of commands, or setup
# that get executed before our tests are ran.
before_install:
    - docker build -t tunghoanganh2310/docker-react -f Dockerfile.dev .

# `script` contains all the commands that need to be executed
# to actually run our test suite
script:
    - docker run -e CI=true tunghoanganh2310/docker-react npm run test
